### ISSUE TITLE
Skipping cinematics during combat

### ISSUE THREAD

**Issue by lowpita** [leatrix/leatrix-plus#158]
Hey. Would like to suggest an option for only skipping cinematics out of combat because when skipping in combat there's a lua error popping up, like in sylvanas' for example.

**Comment by leatrix** [comment]
What is the Lua error?
Does the error appear in every cinematic?

**Comment by lowpita** [comment]
I'm not getting the lua error anymore since I disabled the skip cinematics option from the addon. The lua error only happens when the addon skips cinematics during combat.

**Comment by lowpita** [comment]
There you go: 

1x [ADDON_ACTION_BLOCKED] AddOn 'Leatrix_Plus' tried to call the protected function 'CancelScene()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `CancelScene'
[string "@FrameXML/CinematicFrame.lua"]:139: in function `CinematicFrame_CancelCinematic'
[string "*CinematicFrame.xml:82_OnClick"]:1: in function <[string "*CinematicFrame.xml:82_OnClick"]:1>
[string "=[C]"]: in function `Click'
[string "@Leatrix_Plus/Leatrix_Plus.lua"]:1048: in function <Leatrix_Plus/Leatrix_Plus.lua:1045>
[string "=[C]"]: ?
[string "=[C]"]: in function `Show'
[string "@FrameXML/UIParent.lua"]:2806: in function `SetUIPanel'
[string "@FrameXML/UIParent.lua"]:2646: in function `ShowUIPanel'
[string "@FrameXML/UIParent.lua"]:2561: in function <FrameXML/UIParent.lua:2557>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML/UIParent.lua"]:3159: in function <FrameXML/UIParent.lua:3138>
[string "=[C]"]: in function `ShowUIPanel'
[string "@FrameXML/CinematicFrame.lua"]:52: in function <FrameXML/CinematicFrame.lua:42>

Locals:
Skipped (In Encounter)

**Comment by lowpita** [comment]
Also forgot to mention there's like a blur effect during tp loading screens, for example when using a hearthstone, where the loading screen doesn't show up but my screen completly blurs when using the faster movie skip option.

**Comment by leatrix** [comment]
Please list the dungeons and/or raids that show this error because I am not able to replicate it.  If this is happening to anyone else, more feedback would be useful.

There are two types of cut-scenes in Wow - CinematicFrame and MovieFrame.

An example of a CinematicFrame cut-scene is the cut-scene in Bloodmaul Slag Mines (after Magmolatus is killed).  

An example of a MovieFrame cut-scene is any of the movies in the Media > Movies section of LTP.  All of the movies listed there are of MovieFrame type..

I tested LTP with both of these cut-scene types, during combat, and could not reproduce the error.  I even replaced the CancelScene function with a custom function and it still worked correctly so I'm wondering if something else is causing it or perhaps this particular raid encounter does something specific that is causing it.

LTP only skips cut-scenes in dungeons automatically if you have the 'Skip instance movies automatically' setting checked (in the 'Faster movie skip' configuration panel).  If you don't have that checked, cut-scenes won't be skipped automatically and will require a keypress to skip (such as space, enter or escape).

So if you uncheck the 'Skip instance movies automatically' setting, you should not see an error when the cut-scene plays but if you press space, enter or escape to skip the cut-scene, does the error show?

Reloading your UI with /reload will clear any of these errors from memory.

**Comment by lowpita** [comment]
Hey. I only had this error popping up during Sylvanas Sanctum of Domination raid cinematic because I think that's the only cinematic that plays during combat nowadays, at least for current retail content. I had this problem for a very long time but didn't bother reporting it because it wasn't something that I thought could break my UI or something. This same Lua error also happens when using bigwigs/dbm skip cinematics during combat so I disabled that. Will test today if having the instance option unchecked

**Comment by lowpita** [comment]
Hey. Oops I miss clicked that. I had this error popping up for a very long time, at least for since Sylvanas Sanctum of Domination raid encounter was introduced into retail. Didn't bother reporting it because I thought it wasn't some that would break my UI and I found the option using for skipping scenes fast without doing the prompt steps. Bigwigs/dbm has an option that does the same thing and throws the same lua error when cinematics are skipped during combat, so I disabled all of them before reporting but had only leatrix' checked. Today I'll test if having the instance option unchecked and skipping by keypressing would pop any errors.

**Comment by lowpita** [comment]
Tested it on sylvanas with the skip instance movies automatically option off by skipping with the keypressing buttons and didn't get any lua errors, then enabled the option and had the same error.

**Comment by leatrix** [comment]
In 10.0.13.alpha.3, the 'Skip instance movies automatically' checkbox will be ignored during the Sylvanas fight (so during that fight, you will need to press space, enter or escape to skip the cut-scene).  From what you have said (assuming your last test wasn't a fluke), this should solve the problem.  I didn't test this so perhaps you could enable the 'Skip instance movies automatically' checkbox and let me know if that fixes it in the Sylvanas fight.  From what you have said, this issue seems restricted to the Sylvanas fight but if you do happen to come across it with any other cinematic, do let me know.

**Comment by lowpita** [comment]
Ok. Thanks for the work you've put into this :) I'll test this next week reset and let you know if everything is fine

**Comment by lowpita** [comment]
Hi. Today I tested both options enabled in sylvanas and it's working fine withou lua errors, aswell as keypressing cinematic skip is working too. Still having the screen blurring during loading screens when leaving LFR groups (see https://imgur.com/YypKzbT). I think this only happens when having the "skip instance movies automatically" as I don't seem to reproduce this without that checked, also doesn't happen during every loading screen, mostly leaving/entering LFR group ones.

**Comment by leatrix** [comment]
Is it a drunken blur?  Enable 'Disable screen effects' ('System') and see if the blurred screen comes back.  If you are able to make a video of the problem, that will help too.

**Comment by lowpita** [comment]
It's not a drunken effect because I also have that option enabled. My screen completly blurs (see https://i.imgur.com/ofOKRKi.png) and I can't move my character as I am in the loading screen, the blur stops when the invisible loading screen finishes.

**Comment by lowpita** [comment]
Did LFR for the sake of the clip lol: https://medal.tv/games/world-of-warcraft/clips/JvqlOjpw9Fowm/d1337pgM3m0f
Before entering the instance I got a normal loading screen. So the blur effect indeed only happens after there's a skippable cinematic which is skipped by leatrix (see https://medal.tv/games/world-of-warcraft/clips/Jvr4z3ya2U5D4/d1337Y1L3zDv), after disabling it I didn't get any blurs during loading screens whatsoever.

**Comment by lowpita** [comment]
Did LFR for the sake of the clip lol: https://medal.tv/games/world-of-warcraft/clips/JvqlOjpw9Fowm/d1337pgM3m0f
Before entering the instance I got a normal loading screen. So the blur effect indeed only happens after there's a skippable cinematic which is skipped by leatrix (see https://medal.tv/games/world-of-warcraft/clips/Jvr4z3ya2U5D4/d1337Y1L3zDv), after disabling it I didn't get any blurs during loading screens whatsoever. Forgot to note that in this last clip I didn't get the full loading screen because the boss was alread encountered as you can see in chat, but the loading screen was there which didn't happen to be before.

**Comment by leatrix** [comment]
I just completed the Sylvanas (Sanctum of Domination) fight in LFR and Rygelon fight (Sepulcher of the First Ones) in LFR.  'Skip instance movies automatically' was checked.  There was no graphics corruption at all.  It all worked very smoothly.  However, there were no loading screens.  When the game would normally have shown a loading screen, it didn't show anything.  The game just paused instead.  But a few seconds later, the game returned as normal with no corruption.  So when I left the raid, usually I would expect a loading screen while Dalaran loads but there was nothing, just a pause.

I'm using DirectX12 mode in the graphics settings with an Nvidia 2080.  I don't have any hard drives.  Everything is installed to SSD.  No slow-downs or corruption at all.  Just a screen freeze when loading screens would normally be shown but that only lasted a few seconds then I continued the game as usual.  So it's a mystery.  You originally said that it only happens in Sanctum of Domination but one of the videos showing the freezing is Sepulcher of the First Ones.

**Comment by leatrix** [comment]
And just completed a full Domination's Grasp run (3 bosses) with no issues.  'Skip instance movies automatically' was checked.  Again, there were no loading screens - just pauses where the loading screens would normally appear.  But the game continued after a few second pause with no corruption.

**Comment by lowpita** [comment]
Hi. I originally said it started happening in SoD because that was when I think cinematics started playing during raid encounters or after them and then I enabled the skip option in leatrix as I've been using the addon for years without that checked because usually addons like bigwigs and dbm did that automatically too. Nowadays I use bigwigs but if I enable the skip cinematic option it doesn't trigger the blur effect during loading screens. I don't think my files are corrupted nor my graphics card is the issue because I reproduced this same behavior on my laptop with other Nvidia graphics, another UI, and had the same blur effect and all while still having the game installed on a SSD in both computers. Also I noticed that when the blurry screen happens my loading screens would load faster than the normal ones. But yeah that's a mystery to solve I guess. Will let you know if running with no addons but leatrix plus (which is a problem for me since I have binds and nameplates depending on it) will trigger the same issue. Thank you for your time and the work you put into this :)

**Comment by lowpita** [comment]
Also if that helps I'm using DirectX 12 too on a 3070 in my main computer and 1050 ti on my laptop.

**Comment by leatrix** [comment]
Yes, it's a mystery so far.  I'll do another couple of runs sometime and see if there's any change.  It's easy enough in LFR as tank.  Just a matter of standing still for 10 minutes pressing whichever button is available until the boss falls over.

In the meantime, if anyone else reading this also has the same problem, let me know.

**Comment by leatrix** [comment]
Many thanks for your perseverance in reporting this issue.  After a bit more testing, the 'Skip instance movies automatically' setting has been removed in 10.0.15 since it caused problems with loading screens which in-turn led to strange things happening such as your graphics corruption.

**Comment by lowpita** [comment]
Hey. As always thank you for your time, patience and specially all the work you put into your addons! :)
